language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v8
  - v6
before_install:
  - npm install -g coveralls @patrickhulce/scripts
script:
  - npm run test:lint
  - npm run test:coverage
after_success:
  - cat ./coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
  - hulk npm-publish --yes
